texts = {
    "folder_id": "1uaslUJGg9dQLCqc31l7xAG-dYtO4-2Po",
    "Stream": ("Stream", "Transmitir"),
    "Record": ("Record", "Grabar"),
    "Markers": ("Start/Stop Markers Stream", "Iniciar/Detener Transmisión de Marcadores"),
    "RecordTime": ("Record Time", "Tiempo de grabación"),
    "UploadConfirmation": ("You're about to upload the files to the Google Drive.\nAre you sure you want to do this?\nIf not, no file will be saved in your system. :)", "Estás por subir los archivos al Drive.\n¿Seguro que deseas contnuar?\nSi no, ningún archivo se guardará en tu computadora. :)"),
    "languageSettings": ("Language", "Idioma"),
    "languages": ("English", "Español"),
    "settings": ("Settings", "Configuración"),
    "status": ("Status:", "Estado:"),
    "recording": ("Recording", "Grabando"),
    "finished": ("Finished", "Finalizado"),
    "waiting": ("Waiting", "Esperando"),
    "Face": ("Face", "Rostro"),
    "EEG": ("EEG", "EEG"),
    "Both": ("Both", "Ambos"),
    "nameFormat": ("Camelcase format, no accents", "Formato camelcase, sin acentos"),
    "namePlaceholder": ("JaneDoe", "JuanaPerez")
}
